dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6 

script:
  - export CXX=/usr/bin/g++-6
  - export CC=/usr/bin/gcc-6
  - mkdir build && cd build
  - $CXX ../test/test1.cpp -o test1
