dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - git

before_install:
  - pip install --user cpp-coveralls

script:
  - export GTEST_INSTALL_PATH="$PWD/usr/local"
  - mkdir -p "$GTEST_INSTALL_PATH"
  - mkdir extra && pushd extra
  - git clone --depth 1 https://github.com/google/googletest.git -b v1.8.x
  - git clone --depth 1 https://github.com/boostorg/boost.git -b boost-1.68.0
  - pushd googletest
  - mkdir build && pushd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$GTEST_INSTALL_PATH" ..
  - make -j
  - make install
  - popd
  - popd
  - popd
  - export EXTRACFLAGS="-I$GTEST_INSTALL_PATH/include"
  - export EXTRALFLAGS="-lgtest_main -lgtest -lpthread -L$GTEST_INSTALL_PATH/lib"
  - export COVFLAGS="--coverage"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GTEST_INSTALL_PATH/lib"
  - export CFLAGS=$EXTRACFLAGS
  - export CXXFLAGS=$EXTRACFLAGS
  - export CXX=/usr/bin/g++-6
  - export CC=/usr/bin/gcc-6
  - mkdir build && pushd build
  - $CXX $CXXFLAGS ../test/test2.cpp $EXTRALFLAGS -o test2 $COVFLAGS
  - ./test2
  - popd

after_success:
  - coveralls --root . -E ".*/extra/.*" -E ".*/usr/.*"
