dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - git

before_install:
  # Get the tool used to upload coverage results to coveralls
  - gem install coveralls-lcov
  # Set the prefix used to install googletest, set the source
  # directory and get the source code
  - export GTEST_DIR="$PWD/extra/googletest"
  - export GTEST_SRC_DIR="$GTEST_DIR/source"
  - mkdir -p "$GTEST_DIR" "$GTEST_SRC_DIR"
  - pushd "$GTEST_SRC_DIR"
  - git clone --depth 1 https://github.com/google/googletest.git -b v1.8.x .
  - popd
  # Get boost
  - export BOOST_DIR="$PWD/extra/boost"
  - mkdir -p "$BOOST_DIR"
  - pushd "$BOOST_DIR"
  - git clone --depth 1 https://github.com/boostorg/boost.git -b boost-1.68.0 .
  - popd
  # Get LLCOV
  - export LCOV_DIR="$PWD/extra/lcov"
  - mkdir -p "$LCOV_DIR"
  - pushd "$LCOV_DIR"
  - wget https://github.com/linux-test-project/lcov/archive/v1.12.zip
  - unzip v1.12.zip
  - LCOV="$PWD/lcov-1.12/bin/lcov --gcov-tool gcov-6"
  - popd
  # Change the clone directory
  - mkdir project && cd project
  - export PROJECT_DIR="$PWD"

before_script:
  # Build and install googletest
  - pushd "$GTEST_SRC_DIR"
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$GTEST_DIR" .
  - make -j
  - make install
  - popd

script:
  # Print some information
  - echo "Current dir is $PWD"
  - echo "Project dir is $PROJECT_DIR"
  - echo "GTest dir is $GTEST_DIR"
  - echo "Boost dir is $BOOST_DIR"
  # Set compiler
  - export CXX=/usr/bin/g++-6
  # Set compiler flags
  - export CXXFLAGS="-I$GTEST_DIR/include"
  - export CXXFLAGS="$CXXFLAGS -I$GTEST_DIR/include"
  # Set linker flags
  - export LDFLAGS="-lgtest_main -lgtest -lpthread -L$GTEST_PATH/lib"
  # Set coverage flags
  - export COVFLAGS="--coverage"
  # List directory
  - ls -l
